from pathlib import Path

from ..classes.types.color import Color

# Simulation constants
SCREEN_SCALE_FACTOR = 2
RESOLUTION_SCALE_FACTOR = 4
FPS = 120
SIMULATION_STEPS_PER_FRAME = 1
TIME_SCALE = 0.25

# Physics constants
DEFAULT_GRAVITY = 1000
DEFAULT_DENSITY = 1
DEFAULT_FRICTION = 0.5
DEFAULT_RESTITUTION = 0.5
DEFAULT_ANGULAR_DAMPING = 0.0
DEFAULT_LINEAR_DAMPING = 0.0
SIMULATION_EXAMPLE_DURATION = 5
SOLUTION_INTRODUCTION_TIME = 2

# Solutions constants
MIN_RADIUS = 5
MAX_RADIUS = 20
MAX_ATTEMPTS = 10000

# Aspect constants
FONT_SIZE = 36
PADDING_X = 20  # Horizontal padding
PADDING_Y = 60  # Vertical padding (extra space for buttons)
