# Simulation constants
SCREEN_SCALE_FACTOR = 2
RESOLUTION_SCALE_FACTOR = 4
FPS = 120
TIME_SCALE = 0.25
SCENE_DIMENSIONS = (256, 256)

# Physics constants
DEFAULT_Y_GRAVITY = 981
DEFAULT_DENSITY = 1
DEFAULT_FRICTION = 0.8
DEFAULT_ELASTICITY = 0.5
DEFAULT_ANGULAR_DAMPING = 0.0
DEFAULT_LINEAR_DAMPING = 0.0
SPACE_ITERATIONS = 20

# Solutions constants
MIN_RADIUS = 5
MAX_RADIUS = 40
MAX_ATTEMPTS = 10000
SIMULATION_DURATION_THRESHOLD = 20.0
COLLISION_DURATION_THRESHOLD = 3.0

# Candidates balance
NUMBER_OF_GOOD_CANDIDATES = 5
NUMBER_OF_BAD_CANDIDATES = 5

# Aspect constants
FONT_SIZE = 36
PADDING_X = 20  # Horizontal padding
PADDING_Y = 60  # Vertical padding (extra space for buttons)
