# Simulation constants
SCREEN_SCALE_FACTOR = 3
RESOLUTION_SCALE_FACTOR = 5
FPS = 60
TIME_SCALE = 1
STOP_VELOCITY_THRESHOLD = 0.1
FRAMES_FOR_STATIC_EARLY_STOP = 400
MAX_STEPS = 3000
GOAL_COLLISIONS_REQUIRED = 360

# Physics constants
SCENE_DIMENSIONS = (256, 256)
DEFAULT_Y_GRAVITY = 9.81
DEFAULT_DENSITY = 0.25
DEFAULT_FRICTION = 0.5
DEFAULT_ELASTICITY = 0.20
DEFAULT_ANGULAR_DAMPING = 0.01
DEFAULT_LINEAR_DAMPING = 0.0
VELOCITY_ITERATIONS = 10
POSITION_ITERATIONS = 10

# Solutions constants
MIN_RADIUS = 2
MAX_RADIUS = SCENE_DIMENSIONS[1] // 8
MAX_ATTEMPTS = 10000
