# Simulation constants
RESOLUTION_SCALE_FACTOR = 2.5
FPS = 60
TIME_SCALE = 0.25
SCENE_DIMENSIONS = (256, 256)
VELOCITY_ITERATIONS = 8  # typical default
POSITION_ITERATIONS = 3  # typical default

# Physics constants
DEFAULT_Y_GRAVITY = 980
DEFAULT_DENSITY = 0.25
DEFAULT_FRICTION = 0.5
DEFAULT_ELASTICITY = 0.2
DEFAULT_ANGULAR_DAMPING = 0.01
DEFAULT_LINEAR_DAMPING = 0.0

# Solutions constants
MIN_RADIUS = 2
MAX_RADIUS = SCENE_DIMENSIONS[1] // 8
MAX_SIMULATION_STEPS = 1000
MAX_ATTEMPTS = 10000
COLLISION_DURATION_THRESHOLD = 3 * FPS
