# Simulation constants
SCREEN_SCALE_FACTOR = 3
RESOLUTION_SCALE_FACTOR = 6
FPS = 120
TIME_SCALE = 0.25
STOP_VELOCITY_THRESHOLD = 2
FRAMES_FOR_STATIC_EARLY_STOP = 360
MAX_STEPS = 1500
COLLISION_WINDOW_SIZE = 360
REQUIRED_COLLISIONS = 280

# Physics constants
SCENE_DIMENSIONS = (256, 256)
DEFAULT_Y_GRAVITY = 980
DEFAULT_DENSITY = 0.25
DEFAULT_FRICTION = 0.52
DEFAULT_ELASTICITY = 0.20
DEFAULT_ANGULAR_DAMPING = 0.01
DEFAULT_LINEAR_DAMPING = 0.0
VELOCITY_ITERATIONS = 15
POSITION_ITERATIONS = 20

# Solutions constants
MIN_RADIUS = 2
MAX_RADIUS = SCENE_DIMENSIONS[1] // 8
MAX_ATTEMPTS = 10000
COLLISION_DURATION_THRESHOLD = 30
